//! Phase 5 — embedding generation for log samples.
//!
//! Two embedding namespaces are produced per sample:
//!
//! * **Content embeddings** — dense semantic vector over the raw log text,
//!   generated by an OpenAI-compatible `/v1/embeddings` endpoint.
//!   Stored in the `content_embeddings` MongoDB collection.
//! * **Behavioral embeddings** — a fixed-size ([`behavioral::BEHAVIORAL_DIM`])
//!   feature vector derived from entity type histograms, semantic role
//!   distributions, relation graph density, and the agentic signal score.
//!   Computed locally with no API call.
//!   Stored in the `behavioral_embeddings` collection.
//!
//! Both vectors are passed to [`crate::output::vector::write`] for persistence
//! once the Phase 6 vector output adapter is implemented.
//!
//! # Usage
//! ```rust,ignore
//! let worker = EmbeddingWorker::new(config.embedding.clone())?;
//! let result = worker.embed_sample(
//!     &sample_hash,
//!     &raw_log_content,
//!     &metadata.entities,
//!     &metadata.relations,
//!     metadata.agentic_scan.signal_score,
//! ).await;
//! crate::output::vector::write(&result.sample_hash, result.content_vector, Some(result.behavioral_vector));
//! ```

pub mod behavioral;
pub mod content;

use reqwest::Client;
use serde::{Deserialize, Serialize};
use tracing::warn;

use crate::config::EmbeddingConfig;
use crate::error::AppError;
use crate::models::{EntityRecord, RelationEdge};
use crate::preprocessing::ids;
use mongodb::bson::DateTime;

// ─── Public types ─────────────────────────────────────────────────────────────

/// Distinguishes the two embedding namespaces.
///
/// `Copy` because it is a fieldless two-variant tag that gets threaded through
/// several call layers (handler → repository → collection name); making callers
/// clone it added noise for no safety.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum EmbeddingKind {
    /// Dense semantic vector produced by an external embedding model.
    Content,
    /// Structural feature vector derived from entity/relation statistics.
    Behavioral,
    /// Dense semantic vector over a **task's stated intent** rather than its
    /// transcript (Stage 13).
    ///
    /// The odd one out in two ways. It is keyed on `task_id`, not `sample_hash`,
    /// because a task spans samples. And it embeds one sentence — the goal — where
    /// `Content` embeds the whole blob, which is the point: searching intents
    /// returns tasks with a similar *purpose*, searching transcripts returns tasks
    /// with a similar amount of logging.
    Task,
}

impl EmbeddingKind {
    /// The string used in the embedding id and as the collection discriminator.
    pub fn as_str(&self) -> &'static str {
        match self {
            EmbeddingKind::Content => "content",
            EmbeddingKind::Behavioral => "behavioral",
            EmbeddingKind::Task => "task",
        }
    }
}

/// A persisted embedding record written to MongoDB by the Phase 6 adapter.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EmbeddingRecord {
    /// Stable content-derived identifier (32-hex-char SHA-256 of
    /// `(sample_hash, kind, model)`).  Same sample + same kind + same model
    /// ⇒ same id ⇒ idempotent upsert in `output::vector::write`.
    pub embedding_id: String,
    /// FK to the parent [`crate::models::SampleRecord`].
    ///
    /// For [`EmbeddingKind::Task`] this is the sample the intent text was read
    /// from — provenance rather than the key, since a task spans samples.
    pub sample_hash: String,
    /// FK to the task, set only for [`EmbeddingKind::Task`], where it is the
    /// actual key. `None` for the sample-scoped kinds.
    #[serde(default)]
    pub task_id: Option<String>,
    pub kind: EmbeddingKind,
    /// The dense vector.
    pub vector: Vec<f32>,
    /// Model identifier: e.g. `"text-embedding-3-small"` or `"behavioral-v1"`.
    pub model: String,
    /// Number of dimensions in `vector`.
    pub dimensions: u32,
    pub created_at: DateTime,
}

impl EmbeddingRecord {
    fn new(
        sample_hash: &str,
        kind: EmbeddingKind,
        vector: Vec<f32>,
        model: &str,
    ) -> Self {
        let dimensions = vector.len() as u32;
        // Content-derived embedding_id keyed on (sample_hash, kind, model).
        // Same sample + same kind + same model ⇒ same id ⇒ idempotent upsert.
        // Swapping the model invalidates the id, so re-embedding under a
        // different model inserts a fresh row instead of overwriting.
        let kind_str = kind.as_str();
        let embedding_id = ids::derive_embedding_id(sample_hash, kind_str, model);
        Self {
            embedding_id,
            sample_hash: sample_hash.to_string(),
            task_id: None,
            kind,
            vector,
            model: model.to_string(),
            dimensions,
            created_at: DateTime::now(),
        }
    }

    /// Build a task-intent embedding record.
    ///
    /// Keyed on `task_id` rather than `sample_hash`, since a task spans samples
    /// and there must be exactly one intent vector per task however many samples
    /// it was assembled from. `sample_hash` is retained as provenance: which
    /// sample the intent sentence was actually read from.
    pub fn for_task(
        task_id: &str,
        sample_hash: &str,
        vector: Vec<f32>,
        model: &str,
    ) -> Self {
        let dimensions = vector.len() as u32;
        Self {
            embedding_id: ids::derive_embedding_id(task_id, EmbeddingKind::Task.as_str(), model),
            sample_hash: sample_hash.to_string(),
            task_id: Some(task_id.to_string()),
            kind: EmbeddingKind::Task,
            vector,
            model: model.to_string(),
            dimensions,
            created_at: DateTime::now(),
        }
    }
}

/// Output of a single [`EmbeddingWorker::embed_sample`] call.
#[derive(Debug, Clone)]
pub struct EmbeddingResult {
    /// FK back to the source sample.
    pub sample_hash: String,
    /// Content vector, or `None` if embedding is disabled or the API call failed.
    pub content_vector: Option<Vec<f32>>,
    /// Behavioral vector (always populated — computed locally).
    pub behavioral_vector: Vec<f32>,
}

impl EmbeddingResult {
    /// Convenience: build [`EmbeddingRecord`]s ready for MongoDB insertion.
    pub fn into_records(self, content_model: &str) -> Vec<EmbeddingRecord> {
        let mut records = Vec::with_capacity(2);

        if let Some(cv) = self.content_vector {
            records.push(EmbeddingRecord::new(
                &self.sample_hash,
                EmbeddingKind::Content,
                cv,
                content_model,
            ));
        }

        records.push(EmbeddingRecord::new(
            &self.sample_hash,
            EmbeddingKind::Behavioral,
            self.behavioral_vector,
            behavioral::BEHAVIORAL_MODEL,
        ));

        records
    }
}

// ─── Worker ───────────────────────────────────────────────────────────────────

/// Async worker that generates both content and behavioral embeddings for a
/// single log sample.
///
/// Construct once per service instance (the `reqwest::Client` is internally
/// connection-pooled) and call [`embed_sample`] for each sample that passes
/// the agentic signal threshold.
///
/// [`embed_sample`]: EmbeddingWorker::embed_sample
pub struct EmbeddingWorker {
    config: EmbeddingConfig,
    http:   Client,
}

impl EmbeddingWorker {
    /// Construct a new worker.
    ///
    /// Returns an error if the underlying HTTP client cannot be initialised
    /// (extremely rare on modern operating systems).
    pub fn new(config: EmbeddingConfig) -> Result<Self, AppError> {
        let http = Client::builder()
            .timeout(std::time::Duration::from_secs(30))
            .build()
            .map_err(|e| AppError::Embedding(format!("failed to build HTTP client: {e}")))?;
        Ok(Self { config, http })
    }

    /// Generate content + behavioral embeddings for a single sample.
    ///
    /// * The **behavioral vector** is always computed synchronously from the
    ///   entity/relation data — no network call is made.
    /// * The **content vector** is only generated when `config.enabled` is
    ///   `true` and `config.api_key` is non-empty.  API errors are logged as
    ///   warnings and result in `content_vector = None` rather than propagating
    ///   an error to the caller.
    ///
    /// # Arguments
    /// * `sample_hash`  – stable hash of the parent `SampleRecord`
    /// * `content`      – raw log text (will be truncated per `max_text_chars`)
    /// * `entities`     – typed, classified entities from Stages 6–7
    /// * `relations`    – directed edges from Stage 8
    /// * `signal_score` – agentic signal score from `AgenticScan` (dim 35 of behavioral vec)
    pub async fn embed_sample(
        &self,
        sample_hash:  &str,
        content:      &str,
        entities:     &[EntityRecord],
        relations:    &[RelationEdge],
        signal_score: f64,
    ) -> EmbeddingResult {
        // ── Behavioral vector (always) ─────────────────────────────────────────
        let behavioral_vector = behavioral::compute(entities, relations, signal_score);

        // ── Content vector (only when enabled + key present) ──────────────────
        let content_vector = if self.config.enabled && !self.config.api_key.is_empty() {
            let text = content::truncate(content, self.config.max_text_chars);
            match content::embed(
                &self.http,
                &self.config.api_key,
                &self.config.api_base_url,
                &self.config.model,
                self.config.dimensions,
                &text,
            )
            .await
            {
                Ok(v) => v,
                Err(e) => {
                    warn!(
                        sample_hash,
                        error = %e,
                        "content embedding failed — skipping for this sample"
                    );
                    None
                }
            }
        } else {
            None
        };

        EmbeddingResult {
            sample_hash: sample_hash.to_string(),
            content_vector,
            behavioral_vector,
        }
    }

    /// Embed a task's stated intent (Stage 13).
    ///
    /// Returns `None` — without erroring — when embedding is disabled, no API key
    /// is configured, or the call fails. A task simply has no intent vector in
    /// those cases and is absent from intent search, which is strictly better than
    /// indexing a placeholder that would match queries misleadingly.
    ///
    /// Unlike behavioral embeddings there is no local fallback: the whole point is
    /// semantic similarity of natural-language goals, and that needs a real model.
    pub async fn embed_task_intent(
        &self,
        task_id: &str,
        sample_hash: &str,
        intent_text: &str,
    ) -> Option<EmbeddingRecord> {
        if !self.config.enabled || self.config.api_key.is_empty() {
            return None;
        }

        let text = content::truncate(intent_text, self.config.max_text_chars);
        match content::embed(
            &self.http,
            &self.config.api_base_url,
            &self.config.api_key,
            &self.config.model,
            self.config.dimensions,
            &text,
        )
        .await
        {
            Ok(Some(vector)) => Some(EmbeddingRecord::for_task(
                task_id,
                sample_hash,
                vector,
                &self.config.model,
            )),
            Ok(None) => None,
            Err(e) => {
                warn!(
                    task_id,
                    error = %e,
                    "task intent embedding failed — task will be absent from intent search"
                );
                None
            }
        }
    }
}

// ─── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use std::collections::HashMap;

    use mongodb::bson::DateTime;
    use pretty_assertions::assert_eq;

    use super::*;
    use crate::config::EmbeddingConfig;
    use crate::embedding::behavioral::BEHAVIORAL_DIM;
    use crate::models::{EntityRecord, EntityType, RelationEdge, RelationSource, RelationType,
                        SemanticRole};

    // ── Config helpers ────────────────────────────────────────────────────────

    fn disabled_config() -> EmbeddingConfig {
        EmbeddingConfig {
            enabled: false,
            api_key: String::new(),
            api_base_url: String::new(),
            model: "text-embedding-3-small".to_string(),
            max_text_chars: 8_000,
            dimensions: 1536,
        }
    }

    fn enabled_no_key_config() -> EmbeddingConfig {
        EmbeddingConfig {
            enabled: true,
            api_key: String::new(), // key absent → behaves like disabled
            ..disabled_config()
        }
    }

    // ── Entity / relation builders ────────────────────────────────────────────

    fn make_entity(entity_type: EntityType) -> EntityRecord {
        EntityRecord {
            entity_id: "e".to_string(),
            entity_type,
            semantic_role: SemanticRole::Unknown,
            sample_hash: "sh".to_string(),
            target_id: "t".to_string(),
            trace_id: "trace".to_string(),
            span_id: "span".to_string(),
            parent_span_id: None,
            prov_entity_id: "ug:entity:e".to_string(),
            prov_activity_id: "ug:activity:sh:0".to_string(),
            line_index: 0,
            raw_text: String::new(),
            extracted_fields: HashMap::new(),
            model_id: None,
            tool_name: None,
            mcp_server_id: None,
            token_count: None,
            latency_ms: None,
            timestamp_utc: None,
            content_embedding_id: None,
            behavioral_embedding_id: None,
            task_id: String::new(),
            correlation_key: None,
        }
    }

    fn make_relation(rt: RelationType) -> RelationEdge {
        RelationEdge {
            relation_id: "r".to_string(),
            relation_type: rt,
            source_entity_id: "s".to_string(),
            target_entity_id: "t".to_string(),
            sample_hash: "sh".to_string(),
            confidence: 0.7,
            source: RelationSource::Inferred,
            created_at: DateTime::now(),
        }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Worker construction
    // ─────────────────────────────────────────────────────────────────────────

    #[test]
    fn worker_constructs_with_disabled_config() {
        assert!(EmbeddingWorker::new(disabled_config()).is_ok());
    }

    // ─────────────────────────────────────────────────────────────────────────
    // embed_sample — disabled config
    // ─────────────────────────────────────────────────────────────────────────

    #[tokio::test]
    async fn disabled_worker_returns_none_content_vector() {
        let worker = EmbeddingWorker::new(disabled_config()).unwrap();
        let result = worker
            .embed_sample("hash1", "some log content", &[], &[], 0.5)
            .await;
        assert!(result.content_vector.is_none());
    }

    #[tokio::test]
    async fn disabled_worker_still_computes_behavioral_vector() {
        let worker = EmbeddingWorker::new(disabled_config()).unwrap();
        let entities = vec![make_entity(EntityType::PromptEvent)];
        let result = worker
            .embed_sample("hash2", "log", &entities, &[], 0.8)
            .await;
        assert_eq!(result.behavioral_vector.len(), BEHAVIORAL_DIM);
        // Dim 0 (PromptEvent) should be 1.0
        assert!((result.behavioral_vector[0] - 1.0).abs() < 1e-6);
    }

    #[tokio::test]
    async fn enabled_but_no_api_key_returns_none_content() {
        let worker = EmbeddingWorker::new(enabled_no_key_config()).unwrap();
        let result = worker
            .embed_sample("hash3", "test content", &[], &[], 0.1)
            .await;
        assert!(result.content_vector.is_none(),
                "no api_key → content_vector should be None");
    }

    // ─────────────────────────────────────────────────────────────────────────
    // embed_sample — result metadata
    // ─────────────────────────────────────────────────────────────────────────

    #[tokio::test]
    async fn result_carries_sample_hash() {
        let worker = EmbeddingWorker::new(disabled_config()).unwrap();
        let result = worker
            .embed_sample("my-sample-hash", "content", &[], &[], 0.0)
            .await;
        assert_eq!(result.sample_hash, "my-sample-hash");
    }

    #[tokio::test]
    async fn behavioral_vector_has_correct_dimensionality() {
        let worker = EmbeddingWorker::new(disabled_config()).unwrap();
        let result = worker
            .embed_sample("h", "log", &[], &[], 0.42)
            .await;
        assert_eq!(result.behavioral_vector.len(), BEHAVIORAL_DIM);
    }

    #[tokio::test]
    async fn signal_score_propagated_to_behavioral_dim35() {
        let worker = EmbeddingWorker::new(disabled_config()).unwrap();
        let result = worker
            .embed_sample("h", "", &[], &[], 0.77)
            .await;
        assert!((result.behavioral_vector[35] - 0.77f32).abs() < 1e-5);
    }

    // ─────────────────────────────────────────────────────────────────────────
    // into_records()
    // ─────────────────────────────────────────────────────────────────────────

    #[test]
    fn into_records_content_absent_produces_one_record() {
        let result = EmbeddingResult {
            sample_hash: "sh".to_string(),
            content_vector: None,
            behavioral_vector: vec![0.0; BEHAVIORAL_DIM],
        };
        let records = result.into_records("text-embedding-3-small");
        assert_eq!(records.len(), 1);
        assert_eq!(records[0].kind, EmbeddingKind::Behavioral);
    }

    #[test]
    fn into_records_content_present_produces_two_records() {
        let result = EmbeddingResult {
            sample_hash: "sh".to_string(),
            content_vector: Some(vec![0.1f32; 1536]),
            behavioral_vector: vec![0.0; BEHAVIORAL_DIM],
        };
        let records = result.into_records("text-embedding-3-small");
        assert_eq!(records.len(), 2);
        let kinds: Vec<&EmbeddingKind> = records.iter().map(|r| &r.kind).collect();
        assert!(kinds.contains(&&EmbeddingKind::Content));
        assert!(kinds.contains(&&EmbeddingKind::Behavioral));
    }

    #[test]
    fn into_records_carries_sample_hash() {
        let result = EmbeddingResult {
            sample_hash: "abc123".to_string(),
            content_vector: None,
            behavioral_vector: vec![0.0; BEHAVIORAL_DIM],
        };
        let records = result.into_records("text-embedding-3-small");
        assert!(records.iter().all(|r| r.sample_hash == "abc123"));
    }

    #[test]
    fn into_records_behavioral_uses_behavioral_model_constant() {
        let result = EmbeddingResult {
            sample_hash: "sh".to_string(),
            content_vector: None,
            behavioral_vector: vec![0.1; BEHAVIORAL_DIM],
        };
        let records = result.into_records("text-embedding-3-small");
        let beh = records.iter().find(|r| r.kind == EmbeddingKind::Behavioral).unwrap();
        assert_eq!(beh.model, behavioral::BEHAVIORAL_MODEL);
    }

    #[test]
    fn into_records_dimensions_match_vector_length() {
        let bvec = vec![0.5f32; BEHAVIORAL_DIM];
        let cvec = vec![0.1f32; 512];
        let result = EmbeddingResult {
            sample_hash: "sh".to_string(),
            content_vector: Some(cvec),
            behavioral_vector: bvec,
        };
        let records = result.into_records("text-embedding-3-small");
        for r in &records {
            assert_eq!(r.dimensions as usize, r.vector.len());
        }
    }

    #[test]
    fn embedding_record_ids_are_unique_uuid_v4() {
        let result = EmbeddingResult {
            sample_hash: "sh".to_string(),
            content_vector: Some(vec![0.0; 10]),
            behavioral_vector: vec![0.0; BEHAVIORAL_DIM],
        };
        let records = result.into_records("model");
        let ids: std::collections::HashSet<&str> =
            records.iter().map(|r| r.embedding_id.as_str()).collect();
        assert_eq!(ids.len(), records.len(), "all embedding_ids unique");

        // IDs are now SHA-256(sample_hash, kind, model) truncated to 32 hex
        // chars — no dashes, all lowercase hex.  Verify the new shape.
        for r in &records {
            assert_eq!(r.embedding_id.len(), 32, "32 hex chars");
            assert!(
                r.embedding_id.chars().all(|c| c.is_ascii_hexdigit() && !c.is_uppercase()),
                "lowercase hex only: {}",
                r.embedding_id,
            );
        }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Integration: full pipeline with relations
    // ─────────────────────────────────────────────────────────────────────────

    #[tokio::test]
    async fn integration_openai_shape_behavioral_dims() {
        let worker = EmbeddingWorker::new(disabled_config()).unwrap();
        let entities = vec![
            make_entity(EntityType::PromptEvent),
            make_entity(EntityType::PromptEvent),
            make_entity(EntityType::ToolCallEvent),
            make_entity(EntityType::RetrievalEvent),
            make_entity(EntityType::ToolResultEvent),
            make_entity(EntityType::ContextWindow),
            make_entity(EntityType::CompletionEvent),
        ];
        let relations = vec![
            make_relation(RelationType::PartOf),
            make_relation(RelationType::Generated),
            make_relation(RelationType::RespondedTo),
        ];
        let result = worker
            .embed_sample("openai-hash", "sample content", &entities, &relations, 0.9)
            .await;

        assert_eq!(result.behavioral_vector.len(), BEHAVIORAL_DIM);
        // All values in [0, 1]
        for (i, &x) in result.behavioral_vector.iter().enumerate() {
            assert!((0.0..=1.0).contains(&x), "dim {i} = {x} out of [0, 1]");
        }
        // Entity density: 7 / 50
        assert!((result.behavioral_vector[33] - 7.0 / 50.0).abs() < 1e-5);
        // Relation density: 3 / 200
        assert!((result.behavioral_vector[34] - 3.0 / 200.0).abs() < 1e-5);
    }
}
